source = module ;

module
    =
    | functions {statement}*
    | statement
    ;

statement = {word}+ ;

statements = {statement}* ;

function = '{word}' '(' ')' '{' '{word}+' '}' ;

functions = {function}+ ;

word = {namer}+ ;

namer = letter | digit | under ;

letter = (/[a-z]/ | /[A-Z]/ ) ;

letters = {letter}+ ;

digit = /[0-9]/ ;

digits = {digit}+ ;

under = '_' ;
