
letter = (/[a-z]/ | /[A-Z]/ ) ;

letters = {letter} ;

digit = /[0-9]/ ;

digits = {digit}+ ;

under = '_' ;

namer = letter | digit | under ;

word = {namer}+ ;

statement = {word}* ;

function = '{word}' '(' ')' '{' '{word}+' '}' ;

functions = {function}* ;

module
    =
    | functions statement
    | statement
    ;

source = module ;
